openapi: 3.1.0
info:
  title: Todo API
  summary: A simple API to manage todos
  description: A simple API to manage todos built with Rails in API mode
  version: 1.0.0
  contact:
    name: Bijan Rahnema
    email: bijan@screenisland.com
  license:
    name: MIT
    identifier: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://localhost:3000
    description: Development server
paths:
  /todos:
    get:
      tags:
        - todos
      summary: Get all todos
      description: Returns all todos that have been stored to the database
      operationId: getTodos
      responses:
        200:
          description: A list of todos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        title:
          type: string
          example: Buy milk
        done:
          type: boolean
          example: false
        createdAt:
          type: string
          format: date-time
          example: 2024-01-01T12:00:00Z
        updatedAt:
          type: string
          format: date-time
          example: 2024-01-01T12:00:00Z
      required:
        - title
        - done
